FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*"}

[Project]
Name = "BeefGrunio"
TargetType = "BeefGUIApplication"
StartupObject = "BeefGrunio.Program"

[Platform.Windows]
IconFile = "ico.ico"
Description = "Gruniozerca Meta made with BEEF language."
Company = "Athlon"
Copyright = "Copyright © Athlon 2020"
FileVersion = "1.0"
ProductVersion = "1.0"
